config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :users, only: [:index, :show, :create, :edit, :update] 
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:show, :create, :index]
  resources :posts, except: :index do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end

  resources :cards, only: [:new, :show, :index] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  has_many :comments
  mount_uploader :image, ImageUploader

  def self.search(search)
    return Post.all unless search
    Post.where(['content LIKE ?', "%#{search}%"])
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_one  :card
  has_one :user_address, inverse_of: :user

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  mount_uploader :icon, ImageUploader

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'

  def index
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    # public_key = 'pk_test_f0d7a1fca33f08a051b86659'
    card = Card.where(user_id: current_user.id)
    # redirect_to "new"
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = "sk_test_db2764f9c206b9cfdb4a9888"
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to "/"
      else
        redirect_to action: "pay"
      end
    end
  end

  def show #クレジット購入
    @post = Post.find(params[:id])
    if user_signed_in?
      card = current_user.card
      if card.blank?
        redirect_to action: "new"
        flash[:alert] = '購入にはクレジットカード登録が必要です'
      else

        @post = Post.find(params[:id])
        card = current_user.card
        Payjp.api_key = "sk_test_db2764f9c206b9cfdb4a9888"
        Payjp::Charge.create(
        amount: @post.price, #支払金額
        customer: card.customer_id, #顧客ID
        currency: 'jpy', #日本円
        )

    # if @post.update(status: 1, buyer_id: current_user.id)
    #       flash[:notice] = '購入しました。'
    #       redirect_to "/"
    #     else
    #       flash[:alert] = '購入に失敗しました。'
    #       redirect_to "/"
    #     end

      end
    else

      # redirect_to "/users/sign_up"
      # flash[:alert] = '購入には新規登録が必要です'

    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :move_to_index, except: [:index, :show, :search]

def index
  @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(3)
  @users= User.order("created_at DESC").page(params[:page]).per(4)
  @talk = Post.where(category_id: "2").order("created_at DESC").page(params[:page]).per(3)
  @work = Post.where(category_id: "3").order("created_at DESC").page(params[:page]).per(4)
end

def create
  @post = Post.create!(post_params)
  redirect_to root_path
end

def new
  @post = Post.new
  @parents = Category.all.order("id ASC").limit(4)
end

def show
  @post = Post.find(params[:id])
  @comment = Comment.new
  @comments = @post.comments.includes(:user)
end

def edit
  @post = Post.find(params[:id])

  @category = @post.category
  
end

def update
  post = Post.find(params[:id])
  post.update(post_params)
  redirect_to post_path(post.id)
end

def destroy
  post = Post.find(params[:id])
  post.destroy
  redirect_to root_path
end

def search
  @posts = Post.search(params[:keyword])
end

private

def post_params
  params.require(:post).permit(:title, :image, :price, :category_id, :content).merge(user_id: current_user.id)
end

def move_to_index
  redirect_to action: :index unless user_signed_in?
end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages.where.not(id: current_user.id)
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]

  def index
    @users=User.all
  end

  def create
    @user = User.new(user_params)
  end
  
  def show
    @user =User.find(params[:id])
    @posts = @user.posts

    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  def user_params
    params.require(:user).permit(:icon, :gender, :age, :area, :introduction, :hobby)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/index.html.haml
.container
  .main
    .inner
      %h2 購入確認画面index
      -# = link_to "カードの登録", new_card_path, class: "card-new"
      -# .buy-btn
      -#   = link_to  "/cards/#{@post.id}",class:"buy-btn__link" do
      -#     購入する
      .buy-content
        %p
          %label 販売者
          %span
            = @post.user.name
        %p
          %label 商品名
          %span
            = @post.title
        %p
          %label 価格
          %span
            = @post.price
            %span
            円
      .buy-box
        -# = link_to  "/cards/#{@post.id}",class: "login-btn" do
        -#   購入する
        = link_to  "購入する", post_path(@post.id), class: "buy-btn-last"
      -#   = link_to "購入する", pay_card_path, class: "buy-btn-last"
      .buy-card
        = link_to "カードの登録", new_card_path, class: "card-new"

app/views/cards/new.html.haml
-# .inner
-#   %h2 カード情報入力
-#   .card-register
-#     = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
-#       .card-register__list
-#         %label カード番号
-#         = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
-#       .card-register__list
-#         %label 有効期限
-#         %select#exp_month{name: "exp_month", type: "text"}
-#           %option{value: ""} --
-#           %option{value: "1"}01
-#           %option{value: "2"}02
-#           %option{value: "3"}03
-#           %option{value: "4"}04
-#           %option{value: "5"}05
-#           %option{value: "6"}06
-#           %option{value: "7"}07
-#           %option{value: "8"}08
-#           %option{value: "9"}09
-#           %option{value: "10"}10
-#           %option{value: "11"}11
-#           %option{value: "12"}12
-#         %span 月/
-#         %select#exp_year{name: "exp_year", type: "text"}
-#           %option{value: ""} --
-#           %option{value: "2019"}19
-#           %option{value: "2020"}20
-#           %option{value: "2021"}21
-#           %option{value: "2022"}22
-#           %option{value: "2023"}23
-#           %option{value: "2024"}24
-#           %option{value: "2025"}25
-#           %option{value: "2026"}26
-#           %option{value: "2027"}27
-#           %option{value: "2028"}28
-#           %option{value: "2029"}29
-#         %span 年

-#       .card-register__list
-#         %label セキュリティコード
-#         = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
-#       #card_token
-#         = submit_tag "追加する", id: "token_submit", class:"card-register-btn"
.container
  .main
    .inner
      -# %h2 購入完了画面
      -# .buy-content
      -#   %p
      -#     %label 販売者
      -#     %span
      -#       = @post.user.name
      -#   %p
      -#     %label 商品名
      -#     %span
      -#       = @post.title
      -#   %p
      -#     %label 価格
      -#     %span
      -#       = @post.price
      -#       %span
      -#       円
      %h2 カード情報入力
      .card-register
        = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          .card-register__list
            %label カード番号(4242424242424242でお願いします)
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          .card-register__list
            %label 有効期限
            %select#exp_month{name: "exp_month", type: "text"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span 月/
            %select#exp_year{name: "exp_year", type: "text"}
              %option{value: ""} --
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span 年
          .card-register__list
            %label セキュリティコード
            = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          #card_token
            = submit_tag "購入する", id: "token_submit", class:"card-register-btn"

app/views/cards/show.html.haml
.inner
  %h2 購入確認画面
  -# = link_to "カードの登録", new_card_path, class: "card-new"
  -# .buy-btn
  -#   = link_to  "/cards/#{@post.id}",class:"buy-btn__link" do
  -#     購入する
  .buy-content
    %p
      %label 販売者
      = @post.user.name
    %p
      %label 商品名
      = @post.title
    %p
      %label 価格
      = @post.price 
  .login-btn
    -# = link_to  "/cards/#{@post.id}",class: "login-btn" do
    -#   購入する
    = link_to  "/",class: "login-btn" do
      購入する
  .buy-card
    = link_to "カードの登録", new_card_path, class: "card-new"

app/views/posts/_post.html.haml
-# .content_post{:style => "background-image: url(#{post.image});"}
-#   .post_content
-#     -# %span= image_tag 'arrow_top.png'
-#     %ul.more_list
-#       %li
-#         = link_to '詳細', "/posts/#{post.id}", method: :get
-#       - if user_signed_in? && current_user.id == post.user_id
-#         %li
-#           = link_to '編集', "/posts/#{post.id}/edit", method: :get
-#         %li
-#           = link_to '削除', "/posts/#{post.id}", method: :delete
-#   = simple_format(post.content)
-#   %span.name
-#     %a{:href => "/users/#{post.user.id}"}
-#       %span 投稿者
-#       = post.user.name
.content_row
  %h2 検索結果
  - @posts.each do |post|
    .content
      .content__top
        = image_tag post.image.url, size: "500x300", class: "image" if post.image.present?
      .content__bottom
        .content__title
          = link_to post.title, post_path(post.id), class: "title"
        .content__text
          = post.content
        .content__user
          投稿者:
          = post.user.name
  -# = paginate @posts

app/views/posts/_side.html.haml
.side-top
  %h2 サイドバー
  %h3 カテゴリー(調整中)
  .side-middle__category
    -# = form_with model: @post, class: :form, local: true do |form|
    -#   = form.collection_select(:category_id, Category.all, :id, :name, {prompt: "---"}, {id: "grand_child"})
    -#   = form.submit "検索", class: "search-btn"
    .side-middle__category-content
      %i#user.fa.fa-angle-double-right
      = link_to "会いたい", "#", class: "menu-list"
    .side-middle__category-content
      %i#user.fa.fa-angle-double-right
      = link_to "話たい", "#", class: "menu-list"
    .side-middle__category-content
      %i#user.fa.fa-angle-double-right
      = link_to "働きたい", "#", class: "menu-list"
    .side-middle__category-content
      %i#user.fa.fa-angle-double-right
      = link_to "参加したい", "#", class: "menu-list"
    .side-middle__category-content
      -# = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
        -# = form.text_field :keyword, placeholder: "検索したいカテゴリーid", class: "search-input"
        -# = form.collection_select(:keyword, Category.all, :id, :name, {prompt: "---"}, {id: "grand_child"})
        -# = form.submit "検索", class: "search-btn"

      -# = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
      -#   = form.text_field :keyword, placeholder: "検索したいカテゴリーid", class: "search-input"
        -# = form.collection_select(:category_id, Category.all, :id, :name, {prompt: "---"}, {id: "grand_child"})
    -#   %i#user.fa.fa-angle-double-right
    -#   = link_to "自己啓発", "#", class: "menu-list"
    -# .side-middle__category-content
    -#   %i#user.fa.fa-angle-double-right
    -#   = link_to "投資情報", "#", class: "menu-list"
.side-middle
  %h3

.side-bottom
  %h3 フォローした人
  -# .side-bottom-content
  -#   .side-bottom-content-text
  -#   %i#user.fa.fa-angle-double-right
  -#   .side-bottom-content-title
  -#   aaaaa
  -# .side-bottom-content
  -#   .side-bottom-content-text
  -#   %i#user.fa.fa-angle-double-right
  -# .side-bottom-content
  -#   .side-bottom-content-text
  -#   %i#user.fa.fa-angle-double-right
  -# .side-bottom-content
  -#   .side-bottom-content-text
  -#   %i#user.fa.fa-angle-double-right

-# ユーザー名
-#   - if current_user
-#     = current_user.name
-#   .side-top__user
-#     .side-top__user-image
-#       = image_tag '/material/logo/kid_job_boy_businessman.png', size: "115x115", class: "user-image"
-#     .side-top__user-content
-#       %p フォローユーザー

app/views/posts/edit.html.haml
.container
  .main
    %h2 投稿を編集する
    = form_with model: @post, class: :form, local: true do |form|
      = form.text_field :title, placeholder: :記事のタイトルを入力してください, class: "form-title"
      = form.text_area :content, placeholder: :記事の内容を入力してください, class: "form-text"
      = form.file_field :image, placeholder: "Image Url", class: "form-image"
      = form.collection_select(:category_id, Category.all, :id, :name, {prompt: "---"}, {id: "grand_child"})
      = form.number_field :price, placeholder: "価格を設定してください", class: "form-price"
      = form.submit '公開する', class: "orange-btn"
  -# .side
  -#   = render "posts/side.html"

app/views/posts/index.html.haml
.header-image
  = image_tag '/material/logo/header-image.png', class: "header-photo"
.container
  .side
    = render "posts/side.html"
  .main
    %h2 新着ユーザー
    .user3
      - if @users.present?
        - @users.each do |user|
          .user3-content
            .user3-content__image
              = image_tag user.icon.url, class: "user3-icon" if user.icon.present?
            .user3-content__name
              = link_to user.name, user_path(user.id), class: "content-name"
            .user3-content__title
      = paginate @users
    %h2 新着の投稿
    .user2
      - if @posts.present?
        - @posts.each do |post|
          .user2-content
            .user2-content__image
              = image_tag post.image.url, size: "100×100", class: "content-image" if post.image.present?
            .user2-content__title
              = link_to post.title, post_path(post.id), class: "content-title"
          -# .user2-content__name
          -#   = post.user.name
      = paginate @posts
    %h2 お話しよう
    .user1
      - if @talk.present?
        - @talk.each do |post|
          .user1-content
            .user1-content__image
              = image_tag post.image.url, size: "100×100", class: "content-image" if post.image.present?
            .user1-content__title
              = link_to post.title, post_path(post.id), class: "content-title"
          -# .user1-content__name
          -#   = post.user.name
      = paginate @talk
    %h2 お仕事募集中
    .user4
      - if @work.present?
        - @work.each do |post|
          .user4-content
            .user4-content__left
              .user4-content__left-profile
                .user4-content__left-profile-image
                  = image_tag post.user.icon.url, class: "user4-icon" if post.user.icon.present?
                .user4-content__left-profile-name
                  = post.user.name
              .user4-content__left-work
                .user4-content__left-work-title
                  = link_to post.title, post_path(post.id), class: "content-title"
                .user4-content__left-work-bottom
                  .user4-content__left-work-category
                    %span#category
                      = post.category.name
                  .user4-content__left-work-price
                    %span#text
                      希望単価
                    %span#price
                      = post.price
                    %span#mark
                      円〜
            .user4-content__right
              .tell-btn
                = link_to "詳細を見る", post_path(post.id), class: "syousai-btn"
      = paginate @work

app/views/posts/new.html.haml
.container
  .main
    %h2 新規投稿の作成
    = form_with model: @post, class: :form, local: true do |form|
      = form.text_field :title, placeholder: :記事のタイトルを入力してください, class: "form-title"
      = form.text_area :content, placeholder: :記事の内容を入力してください, class: "form-text"
      = form.file_field :image, placeholder: "Image Url", calss: "form-image"
      %span カテゴリー
      = form.collection_select(:category_id, Category.all, :id, :name, {prompt: "---"}, {id: "grand_child"})
      = form.number_field :price, placeholder: "価格を設定してください", class: "form-price"
      = form.submit '公開する', class: "orange-btn"
  -# .side
  -#   = render "posts/side.html"
  

app/views/posts/search.html.haml
.container
  .main
    -# = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
    -#   = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
    -#   = form.submit "検索", class: "search-btn"
    .content_row
      - @posts.each do |post|
        = render partial: "post", locals: { post: post }
  -# .side
  -#   = render "posts/side.html"

app/views/posts/show.html.haml
.container
  .main
    .post-content-show
      .category-btn
        = @post.category.name
      .postImage
        - if @post.image?
          = image_tag @post.image.url, size: "400x300", class: "post-image"
      .postTitle
        = @post.title
      .post-Text
        = simple_format @post.content
      .postAuthor
        .postAuthor-left
          .postAuthor-left-image
            = image_tag @post.user.icon.url, class: "user4-icon" if @post.user.icon.present?
          .postAuthor-left-name
            = link_to @post.user.name, user_path(@post.user), class: "name-show"
        .postAuthor-right
          .postAuthor-right-price
            %span#text
              希望単価
            %span#price
              = @post.price
            %span#mark
              円
            .aaaaa
              - if user_signed_in? && current_user.id == @post.user_id
                = link_to "編集", edit_post_path(@post.id), class: "postManage__edit"
                = link_to "削除", post_path(@post.id), method: :delete, class: "postManage__delete"
        .postAuthor-buy
          .postAuthor-buy-btn
            = link_to "契約する", new_card_path(@post.id), class: "contract-btn"
      -# .post-buy
      -#   = link_to "契約する", card_path(@post.id), class: "buy-price"
      -# .post-price
      -#   = @post.price
      -#   円
      .comments
        %h4 コメント欄
      - if @comments
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.name, "/users/#{comment.user_id}"
            = comment.text
      - if current_user
        = form_with(model: [@post, @comment], local: true) do |form|
          = form.text_area :text, placeholder: "コメントを入力してください", rows: "2", class: "form-comment"
          = form.submit "コメントする", class: "comment-btn"
      - else
        %strong
          %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
  -# .postManage
  -#     - if user_signed_in? && current_user.id == @post.user_id
  -#       = link_to "編集", edit_post_path(@post.id), class: "postManage__edit"
  -#       = link_to "削除", post_path(@post.id), method: :delete, class: "postManage__delete"
  

app/views/rooms/show.html.haml
.container
  .main
    %h2 メッセージ
    %h4 参加者
    - @entries.each do |e|
      %h5
        %strong
          %a{:href => "/users/#{e.user.id}"}
            = e.user.name
            さん
    %hr/
    - if @messages.present?
      - @messages.each do |m|
        %strong= m.content
        %small
          from
          %strong
            %a{:href => "/users/#{m.user_id}"}
              = m.user.name
              さん
        %hr/
    - else
      %h3.text-center メッセージはまだありません
    = form_for @message do |f|
      = f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70
      = f.hidden_field :room_id, :value => @room.id
      %br/
      = f.submit "投稿する"
    = link_to "ユーザー一覧に戻る", users_path

app/views/users/index.html.haml
.container
  .main
    %h1 登録ユーザー
    - if user_signed_in?
      %h2
        あなたは #{current_user.name}
      - @users.each do |u|
        %p
          %a{:href => "/users/#{u.id}"}
            = u.name
            さん
        %hr/
      = link_to "ログアウト", destroy_user_session_path, :method => :delete
    - else
      = link_to "ユーザーを登録する", new_user_registration_path
      %br/
      = link_to "ログインする", new_user_session_path

app/views/users/show.html.haml
.container
  .main
    .post-content
      %h2
        = @user.name
        さんのプロフィール
      .post-contents
        .post-contents-left
          .user-info
            .status-left
              %p 年齢 
              %p 出身地
              %p 性別
              %p 趣味
              %p 一言
            .status-right
              %p
                = @user.age
              %p
                = @user.area
              %p
                = @user.gender
              %p
                = @user.hobby
              %p
                = @user.introduction
        .post-contents-right
          .user-image
            = image_tag @user.icon.url, class: "user-icon" if @user.icon.present?
          .user-btn 
            - if user_signed_in? && current_user.id == @user.id
              = link_to "編集", edit_user_registration_path, class: "postManage__edit"
            .follow-box
              = render "relationships/follow_button", user: @user, class: "follow"
            .chat-box
              - if @user.id == current_user.id
              - else
                - if @isRoom == true
                  %p2
                    %a{:href => "/rooms/#{@roomId}"} チャットへ
                - else
                  = form_for @room do |f|
                    = fields_for @entry do |e|
                      = e.hidden_field :user_id, :value=> @user.id
                    %p2
                      = f.submit "チャットを始める", class: "chat-btn"
      .user-post
        %h2
          = @user.name
          さんの記事一覧
      - @posts.each do |post|
        .user-content
          .user-content__title
            = link_to post.title, post_path(post.id), class: "user-title"
          .user-content__bottom
            .user-content__category
              %span#category
                = post.category.name
            .user-content__date
              %span#date
                = post.created_at.strftime('%Y/%m/%d')
      = link_to "他のユーザーをみる", users_path, class: "return"