config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :users, only: [:index, :show, :create, :edit, :update] 
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:show, :create, :index]
  resources :posts, except: :index do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end

  resources :cards, only: [:new, :show, :index] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  has_many :comments
  mount_uploader :image, ImageUploader

  def self.search(search)
    return Post.all unless search
    Post.where(['content LIKE ?', "%#{search}%"])
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_one  :card
  has_one :user_address, inverse_of: :user

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  mount_uploader :icon, ImageUploader

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'

  def index
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    # public_key = 'pk_test_f0d7a1fca33f08a051b86659'
    card = Card.where(user_id: current_user.id)
    # redirect_to "new"
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = "sk_test_db2764f9c206b9cfdb4a9888"
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to "/"
      else
        redirect_to action: "pay"
      end
    end
  end

  def show #クレジット購入
    @post = Post.find(params[:id])
    if user_signed_in?
      card = current_user.card
      if card.blank?
        redirect_to action: "new"
        flash[:alert] = '購入にはクレジットカード登録が必要です'
      else

        @post = Post.find(params[:id])
        card = current_user.card
        Payjp.api_key = "sk_test_db2764f9c206b9cfdb4a9888"
        Payjp::Charge.create(
        amount: @post.price, #支払金額
        customer: card.customer_id, #顧客ID
        currency: 'jpy', #日本円
        )

    # if @post.update(status: 1, buyer_id: current_user.id)
    #       flash[:notice] = '購入しました。'
    #       redirect_to "/"
    #     else
    #       flash[:alert] = '購入に失敗しました。'
    #       redirect_to "/"
    #     end

      end
    else

      # redirect_to "/users/sign_up"
      # flash[:alert] = '購入には新規登録が必要です'

    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :move_to_index, except: [:index, :show, :search]

def index
  @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(3)
  @users= User.order("created_at DESC").page(params[:page]).per(4)
  @talk = Post.where(category_id: "2").order("created_at DESC").page(params[:page]).per(3)
  @work = Post.where(category_id: "3").order("created_at DESC").page(params[:page]).per(4)
end

def create
  @post = Post.create!(post_params)
  redirect_to root_path
end

def new
  @post = Post.new
  @parents = Category.all.order("id ASC").limit(4)
end

def show
  @post = Post.find(params[:id])
  @comment = Comment.new
  @comments = @post.comments.includes(:user)
end

def edit
  @post = Post.find(params[:id])

  @category = @post.category
  
end

def update
  post = Post.find(params[:id])
  post.update(post_params)
  redirect_to post_path(post.id)
end

def destroy
  post = Post.find(params[:id])
  post.destroy
  redirect_to root_path
end

def search
  @posts = Post.search(params[:keyword])
end

private

def post_params
  params.require(:post).permit(:title, :image, :price, :category_id, :content).merge(user_id: current_user.id)
end

def move_to_index
  redirect_to action: :index unless user_signed_in?
end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages.where.not(id: current_user.id)
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Apli

    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    -# %script{type:"text/javascript"}Payjp.setPublicKey('pk_test_f0d7a1fca33f08a051b86659');
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.header
      .header-btn
        - if user_signed_in?
          .header-user
            .header-user-fa
              %i#user.fa.fa-user.fa-2x
            .head-user-hidden
              %p
                = link_to "マイページ", edit_user_registration_path(current_user), class: "menu-list"
              %p
                = link_to "フォロー", "#", class: "menu-list"
              %p
                = link_to "メッセージ", "#", class: "menu-list"
              %p
                = link_to "カード登録", "#", class: "menu-list"
              %p
                = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "menu-list"
            .header-user-create
              = link_to "投稿する", new_post_path, class: 'create-btn'
        - else
          .header-user-login
            = link_to "ログイン", new_user_session_path, class: "create-btn"
          .header-user-new
            = link_to "新規登録", new_user_registration_path, class: "create-btn"
      .header-search
        %i#search.fa.fa-search.fa-2x
        .header-search-form
          = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
            = form.text_field :keyword, placeholder: "検索したいキーワード", class: "search-input"
            = form.submit "検索", class: "search-btn"
      = link_to "/" do
        = image_tag '/material/logo/header-logo2.png', size: "100×100", class: "logo"
    %main= yield
    %footer.footer